POST http://localhost:3001/products HTTP/1.1
content-type: application/json

{
    "name": "Product title",
    "manufacturer": "Manu Company",
    "category": "Product category",
    "description": "Product description",
    "price": "0.00",
    "image": ""
}

